### ISSUE TITLE
Paste tabs in background

### ISSUE THREAD

**Issue by Keith94** [cypressious/ff-feedly-open-unread#1]
Hi,
Firstly thanks for the add-on - I've been wanting this for a long time. :)

Now for my request, I'd prefer if the tabs could be opened in the background; i.e. not automatically selected. Could you make that the default behavior, or at least add an option to enable it?
Thanks!

**Comment by cypressious** [comment]
@Keith94 Sounds useful. Would you like to submit a PR? Otherwise, I'll do it when I have time.

**Comment by Keith94** [comment]
I'll have to wait due to lack of JS experience.

**Comment by cypressious** [comment]
Alright, no problem.

**Comment by Keith94** [comment]
Thank you for the quick fix!
