### ISSUE TITLE
Use plus icon for the button

### ISSUE THREAD

**Issue by Keith94** [cypressious/ff-feedly-open-unread#4]
I thought it would be a good idea to change the  "Open Unread" text to simply a `+` icon; this way, it matches the icons beside it (checkmark, reload, etc.).

Also when hovering the button, there can be a tooltip saying "Open Unread" for clarity.

**Comment by cypressious** [comment]
I don't think an icon is a good idea. The "+" typically stands for adding something. An icon should be self-explanatory but finding an icon that says "open unread" would be pretty difficult.

**Comment by Keith94** [comment]
Well, my initial thought process was a `+` would be similar to the "New Tab" button in the browser, i.e. opening new tab(s).

What do you think about either of these icons? 
They can be found here: https://design.firefox.com/icons/viewer/#tab

![image](https://user-images.githubusercontent.com/5490615/40579871-2208b3ae-60e7-11e8-9d49-88cfd091d79a.png)

If not, it's ok to close this. 😛
