### ISSUE TITLE
Add support for Chrome

### ISSUE THREAD

**Issue by Keith94** [cypressious/ff-feedly-open-unread#5]
Any chance this awesome extension can be made available on Chrome?

**Comment by cypressious** [comment]
@Keith94, I've implemented chrome support. You should be able to install it in dev mode. I've also tried publishing it on the Chrome store. I'll report when it's available.

**Comment by Keith94** [comment]
Great! Thank you for the quick fix man.

**Comment by cypressious** [comment]
@Keith94 Should be now available at https://chrome.google.com/webstore/detail/feedly-open-all-unread/blmhlkddebpmcjihpgbnhiinjfibekkf

**Comment by Keith94** [comment]
Woohoo! Works beautifully. Thanks again dude
